# Generated by Django 4.1.2 on 2023-01-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_karyawan', models.CharField(max_length=10)),
                ('nama_lengkap', models.TextField()),
                ('usia', models.IntegerField()),
                ('no_telp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('jabatan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.jabatan')),
            ],
        ),
    ]
