# Generated by Django 4.1.2 on 2023-01-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fungsi_Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungsi_obat', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_obat', models.CharField(max_length=10)),
                ('nama_obat', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=20, null=True)),
                ('stok', models.IntegerField()),
                ('terjual', models.IntegerField()),
                ('harga', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('jenis_obat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='obat.fungsi_obat')),
            ],
        ),
    ]
